# Generated by Django 5.2.6 on 2025-09-20 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
