# Generated by Django 4.2.3 on 2025-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0002_submission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
